pluginManagement {
	repositories {
		maven { url "https://maven.aliyun.com/repository/gradle-plugin" }
		maven { url "https://bmclapi2.bangbang93.com/maven" } // 核心：让 Loom 插件走国内镜像下载 MC
		maven { url "https://maven.fabricmc.net/" }
		gradlePluginPortal()
	}
}

dependencyResolutionManagement {
	repositories {
		maven { url "https://maven.aliyun.com/repository/public" }
		maven { url "https://bmclapi2.bangbang93.com/maven" }
	}
}

// Should match your modid
rootProject.name = 'some-interesting'
